### ISSUE TITLE
Installation Process stuck at 90%

### ISSUE THREAD

**Issue by mrpaddel0815** [outdoorbits/little-backup-box#133]
Hi i am trying to set up LBB - great Tool i think.
But i am stuck at the installation process. Got the raspi to run, ssh controll is active, 
but it gets stuck at 90% at "python3-networkmanager (2.2-1) ..."

Any ideas? Raspi 3B
![Bildschirmfoto 2022-01-14 um 15 28 33](https://user-images.githubusercontent.com/72323200/149531975-dcb376e5-7ce5-426b-a457-83623ea3bb23.png)

**Comment by outdoorbits** [comment]
Never seen that before. Did you try again? What size is your SD?

**Comment by mrpaddel0815** [comment]
Hi, thank you for your quick reply. Yes did everything like your tutorial, got asked to set the mode i will backup and aked if i want to install 2 additional programs (not mentioned in the tutorial, but did it anyway). 32 GB SD and did it like 4 times now...

**Comment by outdoorbits** [comment]
Hi, no idea. python-3-networkmanager seems to be downloaded at this point. Could there be a damage on your card? Could you try another one?

**Comment by outdoorbits** [comment]
I just did a complete installation without any problems.

**Comment by mrpaddel0815** [comment]
i tried it another time, this time without selecting the prefered backup method and did not load the 2 other optional programs on install. But i can only reach the Backend via safari, Chrome is blocking because of a faulty ssl

**Comment by outdoorbits** [comment]
O.K., so this time the installation-process was successful? You can access by https or by http://IP:8000 I just added that to the installation-instructions. So if safari won't allow you to trust the certificate, you can use http at port 8000.

**Comment by outdoorbits** [comment]
... chrome won' t allow you to trust the certificate ... ;-)
