### ISSUE TITLE
Install Process stuck at 84% on python3-networkmanager (2.2-1) ...

### ISSUE THREAD

**Issue by Marown** [outdoorbits/little-backup-box#145]
Hi,
i tried to install little backup box a view times, like in the tutorial, but still every time i got stuck at 84% on python3-networkmanager (2.2-1) ...

![2022-02-23_11h25_42](https://user-images.githubusercontent.com/34144835/155303909-2a2503b2-0ece-42c4-ad3e-52b8e0d7934d.png)

also the raspberry pi is no longer connecting to the network even after restarting so i have to put a new image on the SD Card to try again.

**Comment by Marown** [comment]
Sry forgot
raspberry pi 3 B+
Sandisk Ultra 64GB C10

**Comment by Marown** [comment]
Hi, i did the same thing as in https://github.com/outdoorbits/little-backup-box/issues/133
i tried to install it withou none prefered backup method but still it got stuck at 84%
![2022-02-23_12h31_00](https://user-images.githubusercontent.com/34144835/155311287-0ccdfdaf-a897-4ada-9179-46ce2099ee37.png)

**Comment by Marown** [comment]
I found the Problem, i connected the pi with RJ45 instead of Wifi and also installed the lite OS 32 bit not the 64bit OS that worked for me

**Comment by outdoorbits** [comment]
But this worked for me always. I did most installations on network cable and the last few I installed 64 bit. I will test this tonight.
Did you configure wi-fi by raspberry Imager?

**Comment by Marown** [comment]
Yes I configured the wifi with the raspberry imager. Thanks for your awnser.

**Comment by outdoorbits** [comment]
I tried a new installation on 64 bit lite on cable without any issues. Could you try again to reproduce the problem? Maybe it was a problem about the package or the SD card...?
