### ISSUE TITLE
Oled display issue

### ISSUE THREAD

**Issue by clivetimmins** [outdoorbits/little-backup-box#168]
Every other line on my oled display is missing, like it's being ran at 128x32 not 128x64. I have tried changing it in the python scripts as it seems that 32 is the default inside that ? Dosent seem to have changed anything. 
![20220914_203648](https://user-images.githubusercontent.com/33977302/190246524-31a5cb0c-262b-4aea-ab47-50ecaea7493c.jpg)

**Comment by outdoorbits** [comment]
The display has four lines and it looks exactly like that. The last line is black now but I would expect, it was white when the display started. Just run a backup and I would expect you to see the use of the last line too.

**Comment by outdoorbits** [comment]
New information is printed inverted, old lines are pushed down and printed as you see here in line 3. Outputs using all the screen (like on backup) do not follow this rule.

**Comment by clivetimmins** [comment]
Shouldn't the white box for the inverted text be solid white? Instead of the zebra look it has now?  I should of been more clear I was referring to each line as in the individual pixel lines.

**Comment by outdoorbits** [comment]
Does the last line work while backup?

**Comment by clivetimmins** [comment]
Yes the last line works, just don't know why half the pixels are not showing up.
![20220915_164732](https://user-images.githubusercontent.com/33977302/190449420-83dfe75d-0e81-4c6f-ab94-cded7a44f608.jpg)

**Comment by outdoorbits** [comment]
Sorry, maybe I didn't understand the problem at first. You counted the pixel-lines to be 32 not 64, right? I really didn't do this before but my display doesn't display the black lines as strong as yours. But mine also might not have a 64 lines resolution. I will check this, but this will need some time. Thank you.

**Comment by clivetimmins** [comment]
Thats right its only displaying 32 lines out of 64 I have counted to confirm. The adafruit library is set to 32 by default I think if that helps.

Default is
oled = adafruit_ssd1306.SSD1306_I2C(128, 32, i2c)

I think it should be 
oled = adafruit_ssd1306.SSD1306_I2C(128, 64, i2c)

Not sure if that helps at all. 
Thank you for taking the time on this I appreciate it.

**Comment by clivetimmins** [comment]
I've figured it out. I was editing oled.py in my home folder not the var/www folder. 
![Screenshot_20220915-195140_Termius](https://user-images.githubusercontent.com/33977302/190487344-5e4223ee-8b2a-4192-8966-d2f21383ff92.jpg)
![20220915_195722](https://user-images.githubusercontent.com/33977302/190487348-82945844-0161-4da3-bbff-dcbefc6074ac.jpg)

**Comment by outdoorbits** [comment]
Great, thank you, that's just what I did right now. And I changed the font. Just got so settings-update. Very much nicer!

**Comment by clivetimmins** [comment]
Updating now thanks a bunch ☺️
