### ISSUE TITLE
Log monitor not working

### ISSUE THREAD

**Issue by caso1982** [outdoorbits/little-backup-box#172]
I've just re-installed LBB and have noticed that it doesn't seem to be generating a .log file. 

<img width="629" alt="Screenshot 2022-12-04 220249" src="https://user-images.githubusercontent.com/46815185/205495073-6822b117-f8ad-4baa-826d-23af1a8359b6.png">

**Comment by outdoorbits** [comment]
Did you start any job before?

**Comment by outdoorbits** [comment]
After boot lbb generates an empty logfile and sets the first entry: "Little Backup Box". Did you click on Refresh?

**Comment by caso1982** [comment]
I'd tried starting a transfer job (USB - USB) and it works fine. There was no log file generated though. 
Also tried to refresh and download the log. No result from either.

**Comment by outdoorbits** [comment]
Strange thing. Just to understand, This is a new installation on a newly 
installed latest version of Raspberry Pi OS Lite? Did you do any special 
configuration (including the settings of lbb)? Could you check for the 
logfile by

ls -la /var/www/little-backup-box/tmp/little-backup-box.log

just to check permissions.

**Comment by caso1982** [comment]
This was an update that was overwritten over an older version of LBB (not sure which version) 
Output of ls -la /var/www/little-backup-box/tmp/little-backup-box.log is below. 

-rw-r--r-- 1 root root 337 Dec  5 20:19 /var/www/little-backup-box/tmp/little-backup-box.log

**Comment by caso1982** [comment]
I've just set up the pi again from scratch and completed a fresh install of LBB. All is working and the log is now visible. 
Seems as though trying to update from an older version of LBB using the installer script didn't work properly. 
Thanks for your help.

**Comment by outdoorbits** [comment]
Strange, the file should be owned by user www-data and the 
install-/update-script should set this. Something went wrong, maybe the 
script didn't finish. We'll never know... Have fun!
