### ISSUE TITLE
Log monitor and log files only contain time stamps

### ISSUE THREAD

**Issue by mrsparkle331** [outdoorbits/little-backup-box#178]
**Describe the bug**
When viewing the log monitor in the browser there is no log output. you only see timestamps as the log updates.
When downloading the log file to view locally you see the same.

I did an update at jan 4 21:00 UTC and the behavior is still the same.

**To Reproduce**
open LBB webui.
View the log monitor.

**Expected behavior**
there should be log out put in the log monitor and log files.

**Log monitor and downloaded log file is essentially blank. It only contains time stamps:**

`Little Backup Box
21:22:43

21:22:46

21:22:46

21:22:46

21:22:46

21:22:46

21:22:46

21:22:46

21:22:46

21:22:46

21:22:46

21:22:46

21:22:47

21:22:47

21:22:47

21:22:47

21:22:57

21:22:57

21:23:02
`

**Desktop (please complete the following information):**
 - OS: mac os 13
 - Browser chrome 108.0.5359.124

**Comment by mrsparkle331** [comment]
I have also tried changing the log level between 1,2, and 3. there is no difference

**Comment by outdoorbits** [comment]
I just uploaded some changes a few minutes ago. Would you please update again? Most probably this does not affect your problem but makes debugging easier.

**Comment by outdoorbits** [comment]
... I think I found the bug, it should be fixed now.

**Comment by mrsparkle331** [comment]
working now!
