### ISSUE TITLE
emails are sent using "username"  instead of "sender"

### ISSUE THREAD

**Issue by mrsparkle331** [outdoorbits/little-backup-box#181]
**Describe the bug**
emails are sent using the username value instead of sender value

**To Reproduce**
1. configure email service
2. for this example username is AAA@AAA.com and sender is BBB@BBB.com
3. trigger an email event (test email, boot up, back up job complete, etc...)
4. view the email on recipient end
5. The email received is sent from AAA@AAA.com which is the login username and not the configured sender value.

**Expected behavior**
email should be sent using the "sender" field
in this example the email should be sent from BBB@BBB.com

Instead I see the emails coming in with the "username" value.

**Additional context**
In my case I use a postmaster username to login to my email service and specify a sender email for sent emails.

**Comment by outdoorbits** [comment]
Bug fixed.

**Comment by mrsparkle331** [comment]
verified as fixed
