### ISSUE TITLE
Bug or stupid User?

### ISSUE THREAD

**Issue by ruebyi** [outdoorbits/little-backup-box#183]
Hi, 

I'm not able to get the Email-Notification to work.
I tested
gmx.de
google.com
hosteurope

as Mailprovider - I don't receive mail and can't find any mails in the send Folders of this providers.

What am I doing wrong - I'm using the same settings as I use on my iPhone / iPad for those Accounts

**Comment by outdoorbits** [comment]
Did this work before? I had to change a few things about mailing a few days ago. I'll test against GMX, but maybe not before Monday.
Could you set loglevel to max, mail security to STARTTLS, send a testmail and post the log? Thank you!

**Comment by outdoorbits** [comment]
Does your password contain characters like ", ' or : ?

**Comment by ruebyi** [comment]
It did work with an other Mailprovider, I'm not suing anymore.
But yes, my Passwords have some kind of special Characters - and the working one did not (Except for an "-")

**Comment by ruebyi** [comment]
Here ist the Bug Report - tested GMAIL with STARTLS

`15:40:16
OUTGOING MAIL
> curl --url 'smtps://smtp.gmail.com:465' --ssl-reqd --mail-from '********ww/little-backup-box/tmp/email.txt:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (67) Login denied

15:40:16
Mail:
Greetings from LBB


Congratulations, the mail delivery works.



`

**Comment by ruebyi** [comment]
Tested GMX with SSL

15:42:32
OUTGOING MAIL
> curl --url 'smtps://mail.gmx.net:587' --ssl --mail-from '*****@gmx.de' --mail-rcpt '*********' --user '****@gmx.de':'PASSWORD' --upload-file /var/www/little-backup-box/tmp/email.txt:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

15:42:32
Mail:
Greetings from LBB


Congratulations, the mail delivery works.

**Comment by ruebyi** [comment]
I only deleted the Mailadressen and replaced them - sorry

**Comment by outdoorbits** [comment]
I just updated lbb. This should make passwords more robust, only >'< 
inside a password should cause trouble. For mail.gmx.net I had success 
with port 465, STARTTLS. Does this work for you?

**Comment by smu** [comment]
some problem here. I get a 
` curl: (67) Login denied`
without any special character is my password.

(Didn't know, that you can send mail using curl, btw. very simple solution!)

**Comment by outdoorbits** [comment]
Did you give your username as number or mail-address?

**Comment by smu** [comment]
I have my personal mailserver (exim) where I define username and password myself. 
No numbers and no '@' symbol or other special characters in the username or password.

**Comment by ruebyi** [comment]
the fix worked for dmx - thank you!

**Comment by smu** [comment]
In my case the problem must be related to my server 🙄. When using another mail server it works fine.

**Comment by outdoorbits** [comment]
Does your servers mail logfile tell more?

**Comment by smu** [comment]
Nope, only '535 Incorrect authentication data'

The verbose output of `curl` looks fine as well, including the base64 encoded username:password combination. I don't get it, but it is clearly not an issue in little-backup-box. thanks again!

**Comment by Asturbike** [comment]
I think I only receive emails when the log level is maximum

**Comment by outdoorbits** [comment]
You are right, thank you, bug is fixed.Message ID: 
***@***.***>

**Comment by outdoorbits** [comment]
I'll close this issue now. Thank you for your bug reports.
