### ISSUE TITLE
memory issue or is the pi3 (1GB RAM) not sufficient to run littel-backup-box?

### ISSUE THREAD

**Issue by smu** [outdoorbits/little-backup-box#184]
At the moment pi4 models are hard to get so I though lets use one the pi3 models lying around to test your interesting software.
The installation worked fine, however, when importing photos from my camera the pi3 runs out of memory within minutes.

I know that a pi4 is recommended (due to the USB 3.0 ports). The pi3 has 1 GB of memory. Isn't this enough to run little-backup-box.

Below you can see a screenshot of bpytop, with shows how the systems runs out of memory..

![grafik](https://user-images.githubusercontent.com/207880/212190110-cba4fc17-5dff-41b4-8526-c6727ad86279.png)

**Comment by outdoorbits** [comment]
I didn't check LBB for Pi 3 but there are reports, it's running on Pi zero. So I wouldn't expect problems in Pi 3. Did you install raspbian 32 bit light?

**Comment by smu** [comment]
thanks for the answer and good to know. Yes, I installed raspbian 32 bit light.

Knowing that it should in general be possible to use a Pi 3, I will make a few more tests to understand this issue.

**Comment by outdoorbits** [comment]
Maybe I have a Pi 3 somewhere, if yes, I'll check next week...

**Comment by ruebyi** [comment]
Sorry, I sold my Pi3 two Weeks ago, so I'm not able to test...

**Comment by smu** [comment]
I think I found the problem. Either I have a  problem with the power supply or my external USB hard disc is broken. 
The PI runs out of memory, when the connection to the external drive is lost while importing photos.
Using another drive everything works fine. 

Sorry, I should have checked the log files for this yesterday. Now this issue can be closed as solved, i guess.
thanks for you support!

**Comment by outdoorbits** [comment]
There have been some problems of power supply. Usually they are solved by a powered USB hub. For tested devices have a look at the wiki.
