### ISSUE TITLE
Not asked to install Comitup - no service

### ISSUE THREAD

**Issue by manni0815held** [outdoorbits/little-backup-box#190]
I installed the little backupupbox as told. The installation seems to work fine, except i didn't get asked to install comitup.
After the installation the connection didnt break up. And there is no Comitup Wifi acces point. 
But there are folders with littlebackupbox and tinyfilemanager on the raspberry. But if i try to backup sd cards nothing happens.

![image](https://user-images.githubusercontent.com/118625485/216769725-56d803a0-e61d-4017-ad62-bbc488fc1226.png)

Can anyone help me? I have no idea what im doing or doing wrong :(

Thank you

**Comment by outdoorbits** [comment]
Would you please provide more information? Pi 4, Raspberry Pi OS Lite 32 or 64?

**Comment by manni0815held** [comment]
Pi 4 4gb. Tried both lite 32 and 64, at the moment 64.

**Comment by outdoorbits** [comment]
I just started an installation and everything worked find up to now. I was asked about standard backup method and comitup, everything as expected up to now. You got only one question?

**Comment by outdoorbits** [comment]
How did you try to start your backup?

**Comment by manni0815held** [comment]
No, i got no questions at all.
And i just connected a T5 1TB SSD and then a SD card Reader with sd card. After a while i took the SSD and had a look if anything was copied.

**Comment by outdoorbits** [comment]
Ok, you obviously didn't define a standard backup method? Did you run the installation script as mentioned? How did you install LBB?

**Comment by manni0815held** [comment]
I installed the image via raspberrypi imager. Defined my wifi before that so i could ssh the raspberry. With ssh connection i pasted "curl -sSL https://raw.githubusercontent.com/outdoorbits/little-backup-box/main/install-little-backup-box.sh | bash" in the commandline. I took 20 minutes with no feedback or questions and ended.

**Comment by outdoorbits** [comment]
I just did the same:

By imager I selected "RASPBERRY PI OS LITE (64-BIT), enabled ssh, set a new password for user pi and defined my wifi.
Now I booted this image on my pi and logged in `ssh pi@xxx.xxx.xxx.xxx`.

A few seconds after ` curl -sSL https://raw.githubusercontent.com/outdoorbits/little-backup-box/main/install-little-backup-box.sh | bash  2> install-error.log` I got this screens:

![Screenshot_20230205_091037](https://user-images.githubusercontent.com/45213053/216808727-aa03a797-3b6a-41c5-a316-16a3bd9f53f5.png)
![Screenshot_20230205_091107](https://user-images.githubusercontent.com/45213053/216808728-61fd6dee-ce76-41f5-ae7d-71bc5aa36b72.png)

That's just what it should do.

If you just did the same, there should be equal conditions on both of our raspberry pi's. Maybe your client isn't able to display the dialog? What ssh client are you using?

**Comment by outdoorbits** [comment]
Please ssh to your pi and try this:
`dialog --yesno "test" 5 30`
Does this display a blue dialog?

**Comment by manni0815held** [comment]
Ok, i used WINSCP, that was the problem. Now it worked with putty, the dialog came up.
There is a littlebackupbox Wifi now, but i only can see a site where it says "Choose wifi".

**Comment by outdoorbits** [comment]
Did you try this?

*** Alternatively can reach the web UI of Little Backup Box when you are connected to its
*** hotspot as follows:
*** https://10.41.0.1 (secure, certificate can't be verified automatically, please confirm it)
*** http://10.41.0.1:8000 (insecure)

**Comment by manni0815held** [comment]
I connected to the littlebackupbox wifi. and tried the ip's.
But it just opens a screen where i have to choose one of my own wifis, nothing else.
On PC and on Iphone.

![image](https://user-images.githubusercontent.com/118625485/216820712-41a2b132-b32f-4e5f-ba73-e58312fe0ca7.png)

**Comment by manni0815held** [comment]
Ok, it worked. With the 8000 Port.
Thank you so much. Do i have to close this issues by myself?

**Comment by outdoorbits** [comment]
But if you configure one of these wifis, your lbb will connect to it now and next times. You just have to find out your new IP. This is easier if using a display.
Did you mention, there are differences between http and https? (README)
