### ISSUE TITLE
Big Foto Files Break down. Hi, i tried to Backup large nikon d850 files. 100. the First 30 fast than Slow down and at last break down. Any ideas?

### ISSUE THREAD

**Issue by Stephan1958** [outdoorbits/little-backup-box#222]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by outdoorbits** [comment]
Did you backup from camera or cardreader? At first I don't have an idea, please give more information.

**Comment by AoXis** [comment]
Have you tried to disable the preview?
