### ISSUE TITLE
error code 11, error in file I/O

### ISSUE THREAD

**Issue by an124pilot** [outdoorbits/little-backup-box#228]
Trying to back up a micro sd from a GoPro to a USB flash drive and keep getting the following error. "error code 11, error in file I/O."

No files get backed up at all.

Anyone one have any ideas or suggestions on how to fix this?

**Comment by outdoorbits** [comment]
Most probably it's a power problem. Did you try another cardreader or a powered hub? 
GoPro allows also a camera backup. But it's a bit problematic as it connects to USB only after reinserting the battery.

**Comment by an124pilot** [comment]
I have tried 2 different card readers and the same error occurs, Plugging a canon 7D directly in allows for a backup to occur, but no images get transferred over (it does through the whole process and says backup complete, but then says 0 out of 113 photos copied). Does the Pi not supply enough power through the usb ports to be able to use a card reader? I am using a 3A power supply to power the pi. Also tried a micro sd from a DJI mini 3 drone with no luck. same error. And same error occurs when using a powered usb hub.

**Comment by outdoorbits** [comment]
That's usually the problem. I would suggest to use a powered hub. Please have a look at the wiki.

**Comment by an124pilot** [comment]
That seems to have solved the issue.

One last question, How do I update the internal clock of the software so that it matches the right date and time?

**Comment by outdoorbits** [comment]
I expect this to be done automatically when connecting to the internet... I'm not sure actually. I'm in holiday now but if it doesn't sync time, please tell me. I'll fix that within next two weeks.

**Comment by an124pilot** [comment]
It does not seem to be updating to the correct time. It has the minutes right but not the hours. The hours are about 5 hours ahead. So I am not sure if there is somewhere to set the time zone I am in or not, but if it is updating from internet time, it is not currently doing so.

**Comment by outdoorbits** [comment]
Ok, it's using UTC. Because raspberry can't keep the time, it starts always at unixtime 0 and if you are offline, it will stay in past. Do you need correct time zone? I can add this.

**Comment by an124pilot** [comment]
A Time zone selector would be very handy.

Also a further update to the error 11 issue. The issue seems to have stemmed from trying to copy from a micro sd card from any camera (DJI drone, GoPro, cannon) to a USB flash drive or hard drive formatted in Apple file systems HFS and HFS Plus. When using a hard drive formatted in exFat, the transfer happens with no issues and no powered USB Hub is required.

Further testing on my end shows that transfers will no occur to any target drive that is formatted as Apple file systems HFS and HFS Plus and transfers only work when the source is also in Apple file systems HFS and HFS Plus.

**Comment by outdoorbits** [comment]
File system management and all core components are completely rewritten and I hope it will be ready for a first upload in maybe two weeks. I hope, this problem will be solved then. I hope you will test this and report.

**Comment by outdoorbits** [comment]
The new version is online now, in development branch. Setting time zone is included. Depending on bug reports this might replace the main branch some weeks later.
