### ISSUE TITLE
Unable to login after global password set

### ISSUE THREAD

**Issue by 1bryanw** [outdoorbits/little-backup-box#270]
**Describe the bug**
I installed and all worked fine till I was using phone and set global password. After reboot I was unable to login via web app via  phone.

*I was able to Reproduce twice *
1. Go to reset global password.  ( don't have access don't remember exact phrase, but under settings )
2. Other accounts are fine, ssh and login via console.
3. Launch of connect to LBB via IP I then get a pop-up asking for user name and password.
4.  I used http://IP-lbb ( used IP provided via ifconfig )
5. I tried my user name  bryan and pi, both failed. Tried pi with the default thinking maybe it didn't reset. This failed

**Expected behavior**
login web via IP to LBB

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser: chrome,
 - Version  10.0.19045 Build 19045

**Smartphone (please complete the following information):**
 - Device:  pixel 5 
 - OS: android
 - Browser chrome

**Additional context**
I then looked at logs and found errors with PHP and changing password.

/var/log/apache2/lbb-error.log
[Mon Jan 15 10:07:33.088920 2024] [auth_basic:error] [pid 1358] [client 192.168.2.128:45720] AH01618: user bryan not found: /config.php, referer: http://192.168.2.111/view.php
[Mon Jan 15 10:07:47.892127 2024] [auth_basic:error] [pid 1360] [client 192.168.2.128:41280] AH01618: user pi not found: /config.php, referer: http://192.168.2.111/view.php
[Mon Jan 15 10:08:48.827184 2024] [auth_basic:error] [pid 1358] [client 192.168.2.128:45090] AH01618: user bryan not found: /tools.php, referer: http://192.168.2.111/config.php
[Mon Jan 15 10:14:27.741573 2024] [auth_basic:error] [pid 1357] [client 192.168.2.128:41224] AH01618: user bryan not found: /config.php, referer: http://192.168.2.111/config.php
/var/log/apache2/error.log

and 

Adding password for user lbb
chpasswd: (user pi) pam_chauthtok() failed, error:
Authentication token manipulation error
chpasswd: (line 1, user pi) password not changed
dos2unix: .//var/www/little-backup-box/config.cfg: No such file or directory

The above error references /var/www/little-backup-box/config.cfg
I looked at this file and see  my password as very last item and it is my original password ( maybe just local account and nothing to do with PHP?)

Let me know if you need more info. 

Thanks
Bryan

**Comment by outdoorbits** [comment]
Does your password contain special characters?

**Comment by 1bryanw** [comment]
No special characters only letters and numbers. total 8

**Comment by outdoorbits** [comment]
Witch login fails? Web UI and SSH?

**Comment by 1bryanw** [comment]
Web UI fails.  I just reinstalled so ready for any possible troubleshooting. I'm sure If i try to change global password I can recreate if needed.

**Comment by outdoorbits** [comment]
The user name for the web UI is "lbb".

**Comment by 1bryanw** [comment]
Ok I'll try that after changing global password.  I'll let you know once I give it try in about an hour.
Thanks

**Comment by 1bryanw** [comment]
Ok that was it. I guess I missed that part, but its on documentation so my fault for not catching that.

Thank you so much for quick reply.
Bryan
