### ISSUE TITLE
EN Translation error

### ISSUE THREAD

**Issue by kshapley** [outdoorbits/little-backup-box#277]
**Describe the bug**
The English Language has an error on the Translation of one Line in the EN.json file

**To Reproduce**
On the Home Screen.
Select Maintenance
The Two Buttons (Target & Source) Show as "automatische Auswahl" 

**Expected behavior**
It Should display as "Automatic Selection"

**Screenshots**
In the en.json file. Line 239 the mistranslation shows as:
 "preset_partition_auto": "automatische Auswahl",

Should be:
 "preset_partition_auto": "Automatic Selection",

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: All

**Comment by outdoorbits** [comment]
It's fixed. I'm sure, there must be more errors in translations. If you have better translations, please tell me.
Thank you!
