### ISSUE TITLE
Unable to update. Older versions not supported

### ISSUE THREAD

**Issue by an124pilot** [outdoorbits/little-backup-box#316]
I am trying to update my LBB and haven't don't an update since December and when I try and run the update command I get the following error.

"Sorry: Installation or updates are only possible for Raspberry Pi OS Bookworm. Older versions are no longer supported."

Any work arounds as I would rather not to have reflash and start the whole process over again.

Thanks.

**Comment by outdoorbits** [comment]
There have been relevant changes to bookworm and maintaining both was not possible anymore to me. So unfortunately you would have to write a new SD and install again. But you can export your settings from web UI before, to make the new setup quick and easy.
