### ISSUE TITLE
No thumbnails 

### ISSUE THREAD

**Issue by ruebyi** [outdoorbits/little-backup-box#317]
Hi, 
I‘m traveling right now, and I don‘t get any thumbnails generated of my ORF Files from my OM-1.

![IMG_4103](https://github.com/user-attachments/assets/d38cb527-bdd2-4e45-bd9a-e478f28185c7)

**Comment by outdoorbits** [comment]
I found there is an issue about just this type of files in libraw 0.20 
(actual bookworm version). But there is an updated version having 
positive reports. Let me see if I can fix this.

**Comment by ruebyi** [comment]
Thank you!
Same form raw files from my OM-5

**Comment by ruebyi** [comment]
There is a snapshot with support for Om-5
https://www.libraw.org/news/libraw-202403-snapshot

**Comment by ruebyi** [comment]
And 0.21 seems to support OM-1

**Comment by outdoorbits** [comment]
I hope my solution works for you. Please

1. update to actual version
2. In Settings - Update klick the button 'Update libraw to 0.21.2-2.1'
3. You have to remove all the dummy files from tims folders (thumbnails)
4. Create thumbnails again
5. Tell me if it is working ;-)

**Comment by ruebyi** [comment]
Than you

update I stuck…

[cmd 3.log](https://github.com/user-attachments/files/16433075/cmd.3.log)

**Comment by outdoorbits** [comment]
Did you try to create thumbnails from raw? Maybe the last lines of the update just didn't show up in log?

**Comment by ruebyi** [comment]
Not yet - I can‘t find the dummy files - ca I access them via file browser of lbb?

**Comment by outdoorbits** [comment]
The files into the tims folders below the original images. Every original image has a thumbnail here. Because the original image could not be used, there are alternative grey images I called dummies.

**Comment by ruebyi** [comment]
It worked for my om-5 files, but not for my Om-1…
I will try to delete the whole Tims folder instead of only deleting the jpg (I think that’s the difference between the two folders)

**Comment by outdoorbits** [comment]
But is there a difference to before the modification?

**Comment by ruebyi** [comment]
Yes OM-5 ORF-Files get a preview now

**Comment by outdoorbits** [comment]
This is strange. In the compatibility list of libraw version 0.21 you can find "OM Digital Solutions OM-1" (since 0.21.0) but not OM-5. It should be vice versa.
OM-5 should be supported sice LibRaw 202403 snapshot, which is not available as package but as source code only.

**Comment by ruebyi** [comment]
I just deleted the Tim’s folder completely in the OM-1 folder and rebuild previews. 
it‘s a very long process on a pi Zero 2 W

**Comment by ruebyi** [comment]
It worked! Took my 30hours, but it created all 3000 thumbs

**Comment by outdoorbits** [comment]
Great, have a nice trip!
