### ISSUE TITLE
Just wrong Buttons 

### ISSUE THREAD

**Issue by ruebyi** [outdoorbits/little-backup-box#322]
On the latest release there are a lot of "Save" Buttons on the "View" Page.

Some should be "Forward" or "Next" etc.

Nothing critical - Sorry That I'm not experienced enough to add the solution myself as a contribution.

**Comment by outdoorbits** [comment]
Don't know when and why that happened. It's fixed now, thank you!

**Comment by ruebyi** [comment]
Thank you! I did an Update and it looks fine now!
