### ISSUE TITLE
smartctl requires a device name as the final command-line argument

### ISSUE THREAD

**Issue by black-jmyntrn** [outdoorbits/little-backup-box#323]
I am seeing the below on the gui...

Device status
ERROR:                             smartctl requires a device name as the final command-line argument.

Whats happening is now my hard drive inside the [Siig JU-SA0S12-S1 USB 3.0 to SATA Hard Drive with SD Reader, Storage Enclosure](https://amzn.to/4fIMwUB) cant be seen in LBB... its connected to a [VENTION USB Hub - Multi USB Port Splitter Ultra-Slim Multiport USB 3.0 Hub Adapter](https://amzn.to/3SVSCXL) and as of today none of it works any more... and tips or thoughts to get it working again?

**Comment by outdoorbits** [comment]
I'm travelling now, so my answers might be slow. In witch part of the gui do you read this? Can you repair the partition using the gui tools?
