### ISSUE TITLE
Backup gets stuck at 99.8%

### ISSUE THREAD

**Issue by norbertborsky** [outdoorbits/little-backup-box#344]
**Describe the bug**
When i try to back up from usb to internal storage (microSD card) the backup process always gets stuck at 99.8% (last file). I have tried to let it go for over an hour and nothing happens and tried it multiple times. I use Raspberry Pi 5 8gb, Belkin Devices card reader via usb cable. 
I have tried already to make a completely fresh install of Raspberry Pi but the problem persists.

**To Reproduce**
1. Back up from USB to internal storage

**Expected behavior**
Finishes the backup.

<img width="1336" alt="Screenshot 2024-12-28 at 19 33 33" src="https://github.com/user-attachments/assets/85b1e634-8a9c-4032-b891-143c3fa61bdd" />

**Logs**
`2024-12-28 18:48:13
Ready
Insert sources

2024-12-28 18:48:13
pre mount usb, source (device list changed)
--uuid 6657-E919

2024-12-28 18:48:13
DeviceChosenIdentifier='--uuid 6657-E919' ('/dev/sdc1') prepared to mount at '/media/usb_source', exfat

2024-12-28 18:48:13
MOUNTED?: '/media/usb_source' = False

2024-12-28 18:48:14
mounting:
USB

2024-12-28 18:48:14
mount --uuid 6657-E919 /media/usb_source -o uid=33,gid=33,umask=0

2024-12-28 18:48:14
mounted USB '--uuid 6657-E919' at '/media/usb_source': Msg.=''

2024-12-28 18:48:14
MOUNTED?: '/media/usb_source' = True

2024-12-28 18:48:14
Source o.k.
size: 250G
used: 106G
free: 143G
FS: exfat
 42.6% >>>>>>>>____________

2024-12-28 18:48:14
mount USB device: --uuid 6657-E919

2024-12-28 18:48:14
MOUNTED?: '/media/usb_source' = True

2024-12-28 18:48:14
Backup from usb: 

2024-12-28 18:48:14
Lost target device internal? False

2024-12-28 18:48:14
MOUNTED?: '/media/usb_source' = True

2024-12-28 18:48:14
Lost source device usb? False

2024-12-28 18:48:14
Working...

2024-12-28 18:48:14
rclone check /media/usb_source/ /media/internal/lbb_20241227211544-22969 --config /media/rclone.conf -vv --min-size=1B --ignore-case --no-update-modtime --no-update-dir-modtime --exclude **$recycle.bin/** --exclude **trash** --exclude **.id --exclude **.lbbid --exclude images.db --one-way

2024-12-28 18:48:14

2024-12-28 18:48:14
Files to sync from folder '': 526

2024-12-28 18:48:14
Files to sync before backup: 526

2024-12-28 18:48:14
USB storages 
 > Int. storage 
0 of 526
Time: ?
comparing

2024-12-28 18:48:14
rclone copy /media/usb_source/ /media/internal/lbb_20241227211544-22969 --config /media/rclone.conf -vv --min-size=1B --ignore-case --no-update-modtime --no-update-dir-modtime --exclude **$recycle.bin/** --exclude **trash** --exclude **.id --exclude **.lbbid --exclude images.db

2024-12-28 18:48:16
USB storages 
 > Int. storage 
6 of 526
Time: 0:02:20
 1.1% ____________________

...

2024-12-28 19:11:57
USB storages 
 > Int. storage 
525 of 526, 6.332Mi/s
Time: 0:00:02
 99.8% >>>>>>>>>>>>>>>>>>>_

pi@lbb:/var/www/little-backup-box/tmp $ date
Sat 28 Dec 19:37:53 CET 2024
`

**Comment by outdoorbits** [comment]
There was a bug using the wrong tool for this backup. It used rclone which is for cloud backups. Now that is fixed. Would you please update and tell me? In my tests it worked now without a problem. (But before the changes it didn't stop like it was in your case).

**Comment by outdoorbits** [comment]
Sorry, now it is ready for update.

**Comment by norbertborsky** [comment]
Thank you for the quick reply. I have tried 2 times and now it always gets stuck at 52.6%. Also second issue i wanted to report, when i open the rclone gui it's just a blank white screen (tested on multiple devices).
![Screenshot_20241229_082937_Chrome](https://github.com/user-attachments/assets/47b64947-b839-431a-b34f-35f3e35bedbf)
![Screenshot_20241229_093548_Chrome](https://github.com/user-attachments/assets/fee6cef3-499d-4cf3-ab01-5bf8094a32c6)
![Screenshot_20241229_093900_Chrome](https://github.com/user-attachments/assets/f4bc309d-93f9-4848-995b-0ffa706dbb74)

**Comment by norbertborsky** [comment]
One more update. I let it go for a longer time and after something over 30 mins doing nothing it continued to work. Is that a normal behavior?
![Screenshot_20241229_101513_Chrome](https://github.com/user-attachments/assets/7b8590d1-70e1-4eb4-8d96-ddf469639eac)

**Comment by outdoorbits** [comment]
At first the rclone gui problem: Firefox does not allow to access the embedded rclone gui window for security concerns and as I found now, Chrome does also not allow this anymore. You get there by this link: http://111.222.333.444:81/ (use your IP).
I'm working on that but I'm still facing problems in apache2 webservers configuration. If you or anybody else has this skills, your help would be very appreciated.

The delay of more than half an hour is interesting. The process works after that as expected? Is there maybe a extremely huge file (~70 GB)? Can you copy all the files from your usb to your PC or is there an error message (maybe a corrupted file)?

What's about your free disk space on your SD? Keep in mind, if you have no space left, even the operating system might get unstable. I would recommend not to backup to internal if you have different options.

**Comment by norbertborsky** [comment]
After that pause it continued to work and finished the backup. I include the full log to investigate, the most interesting part is between 9:27 and 10:04 (as you can see it has skipped two files in the log). There is no larger files then a 300MB video.

Regarding the storage, it's a 256gb sd card so there is plenty of room. I plan to install an NVMe drive to use it for the backup, it was just a first testing and found out this bug. I will do some more testing next week.

[little-backup-box.log](https://github.com/user-attachments/files/18269056/little-backup-box.log)
<img width="797" alt="Screenshot 2024-12-29 at 10 48 31" src="https://github.com/user-attachments/assets/fc7051da-19cc-4758-9204-3705274743a8" />

**Comment by norbertborsky** [comment]
Also wanted to mention, I truly appreciate your quick responses and eagerness to assist. Thank you! :)

**Comment by outdoorbits** [comment]
Thank you ;-)
File #278 to #280 does not mean a skip. This is just an issue of not logging every single transfer. It counted #279 silent.

**Comment by outdoorbits** [comment]
Thanks to the help of the ai Claude the web servers config now is working and rclone gui as well as comitup are displayed as expected.

**Comment by norbertborsky** [comment]
looks good! :) i will do some more testing next week with proper hw, this original reported bug is solved so we can close the issue i guess.
